[bot]
token = "..."
src_url = "https://github.com/.../..."

[logging]
dirs = "info,hyper=warn,reqwest=warn,tokio_util::codec=warn"

[chat]
receiver_chat_id = 123

[blacklisted]
domains = ["t.me", "2girls1cup.ca"]

[domains_with_reactions]
domains = [
    "vk.com", "vkvideo.ru", "ok.ru", "rutube.ru", "max.ru", "m.vkvideo.ru",
    "youtube.com", "youtu.be", "m.youtube.com", "music.youtube.com", "studio.youtube.com",
    "vm.tiktok.com", "vt.tiktok.com", "tiktok.com", 
    "instagram.com", "x.com", "facebook.com",
    "rt.pornhub.com", "rt.pornhub.org", "pornhub.com",
    "share.google", "drive.google.com",
    "coub.com",
]

[yt_dlp]
max_file_size = 5000000
executable_path = "./yt-dlp/executable"
cookies_path = "./cookies"

[database]
user = "..."
password = "..."
# You can use "127.0.0.1" if the database is running on the same network.
# If the database is running in docker, you can use the database container name as the host.
host = "ytdl_tg_bot.postgres"
port = 5432
database = "api"

[yt_toolkit]
url = "http://ytdl_tg_bot.yt_toolkit_api:8080"
# url = "http://127.0.0.1:8080"

[yt_pot_provider]
url = "http://ytdl_tg_bot.yt_pot_provider_api:4416"
# url = "http://127.0.0.1:4416"

[telegram_bot_api]
url = "http://ytdl_tg_bot.telegram_bot_api:8081"
# url = "https://api.telegram.org"
api_id = "..."
api_hash = "..."
