[bot]
token = "..."
src_url = "https://github.com/.../..."

[logging]
dirs = "info,hyper=warn,reqwest=warn,tokio_util::codec=warn"

[chat]
receiver_chat_id = 123

[timeouts]
video_download = 420
audio_download = 420
send_by_fs = 210
send_by_id = 360

[blacklisted]
domains = ["t.me", "2girls1cup.ca"]

[domains_with_reactions]
domains = [
    "vk.com", "vkvideo.ru", "ok.ru", "rutube.ru", "max.ru", "m.vkvideo.ru",
    "youtube.com", "youtu.be", "m.youtube.com", "music.youtube.com", "studio.youtube.com",
    "rt.pornhub.com", "rt.pornhub.org", "pornhub.com",
    "vm.tiktok.com", "vt.tiktok.com", "tiktok.com", 
    "x.com", "facebook.com",
    "share.google", "drive.google.com",
    "vxinstagram.com",  "fxtwitter.com", "fixupx.com", "fxbsky.app",
    "coub.com",
]

[random_cmd]
domains = [
    "vk.com", "vkvideo.ru", "ok.ru", "rutube.ru", "max.ru", "m.vkvideo.ru",
    "youtube.com", "youtu.be", "m.youtube.com", "music.youtube.com", "studio.youtube.com",
    "vm.tiktok.com", "vt.tiktok.com", "tiktok.com", 
    "vxinstagram.com", "fxtwitter.com", "fixupx.com", "fxbsky.app",
    "coub.com", 
]

[[replace_domains]]
from = '^(?:.*\.)?instagram\.(tv|net|com|org)$|^instagr\.am$'
to = "vxinstagram.com"

[[replace_domains]]
from = '^(?:.*\.)?twitter\.com$'
to = "fxtwitter.com"

[[replace_domains]]
from = '^(?:.*\.)?x\.com$'
to = "fixupx.com"

[[replace_domains]]
from = '^(?:.*\.)?bsky\.app$'
to = "fxbsky.app"

[yt_dlp]
max_file_size = 5000000
executable_path = "./yt-dlp/executable"
cookies_path = "./cookies"

[database]
user = "..."
password = "..."
# You can use "127.0.0.1" if the database is running on the same network.
# If the database is running in docker, you can use the database container name as the host.
host = "ytdl_tg_bot.postgres"
port = 5432
database = "api"

[yt_toolkit]
url = "http://ytdl_tg_bot.yt_toolkit_api:8080"
# url = "http://127.0.0.1:8080"

[yt_pot_provider]
url = "http://ytdl_tg_bot.yt_pot_provider_api:4416"
# url = "http://127.0.0.1:4416"

[telegram_bot_api]
url = "http://ytdl_tg_bot.telegram_bot_api:8081"
# url = "https://api.telegram.org"
api_id = "..."
api_hash = "..."

[tracking_params]
params = [
    "utm_source",
    "utm_medium",
    "utm_campaign",
    "utm_term",
    "utm_content",
    "utm_id",
    "gclid",
    "gclsrc",
    "dclid",
    "gbraid",
    "wbraid",
    "_ga",
    "_gl",
    "gad_source",
    "gad_campaignid",
    "fbclid",
    "fbadid",
    "fb_action_ids",
    "fb_action_types",
    "fb_source",
    "fb_ref",
    "fb_comment_id",
    "action_object_map",
    "action_type_map",
    "action_ref_map",
    "ttclid",
    "tt_content",
    "tt_medium",
    "tt_adid",
    "tt_adgroupid",
    "tt_campaignid",
    "tt_placement",
    "tt_device",
    "tt_keyword",
    "tt_network",
    "igsh",
    "igshid",
    "ig_rid",
    "epik",
    "ppn",
    "ppss",
    "twclid",
    "t",
    "s",
    "vk_click_id",
    "click_id",
    "mt_app_id",
    "pid",
    "ok_click_id",
    "st.cmd",
    "st.mode",
    "idfa",
    "google_aid",
    "android_id",
    "windows_aid",
    "ip",
    "ua",
    "mcc",
    "mnc",
    "device_manufacturer",
    "device_model",
    "os_name",
    "os_ver",
    "app_ver",
    "qclid",
    "sharedId",
    "asc_subtag",
    "asc_campaign",
    "asc_source",
    "asc_medium",
    "asc_content",
    "asc_term",
    "asc_cid",
    "asc_rid",
    "asc_sid",
    "ob_click_id",
    "msclkid",
    "u",
    "sc_campaign",
    "sc_ad",
    "yclid",
    "ysclid",
    "_openstat",
    "erid",
    "mt_click_id",
    "mt_link_id",
    "mt_campaign",
    "mt_adset",
    "mt_creative",
    "li_fat_id",
    "trk",
    "trkCampaign",
    "trkInfo",
    "rt_destination",
    "af_xp",
    "af_ad",
    "af_adset",
    "af_c_id",
    "af_adset_id",
    "af_ad_id",
    "af_channel",
    "af_siteid",
    "af_sub1",
    "af_sub2",
    "af_sub3",
    "af_sub4",
    "af_sub5",
    "adj_t",
    "adj_label",
    "adj_campaign",
    "adj_creative",
    "_branch_referrer",
    "_branch_match_id",
    "branch_id",
    "mc_cid",
    "mc_eid",
    "_kx",
    "_ke",
    "elqTrackId",
    "elqaid",
    "elqat",
    "elqCampaignId",
    "mkt_tok",
    "_hsenc",
    "_hsmi",
    "__hsfp",
    "__hssc",
    "__hstc",
    "hsCtaTracking",
    "hsa_acc",
    "hsa_ad",
    "hsa_cam",
    "hsa_grp",
    "hsa_kw",
    "hsa_la",
    "hsa_mt",
    "hsa_net",
    "hsa_ol",
    "hsa_src",
    "hsa_tgt",
    "hsa_ver",
    "sm",
    "lv",
    "user",
    "ch",
    "im",
    "so",
    "nc",
    "nw",
    "uid",
    "UPä¸»UID",
    "itscg",
    "itsct",
    "pt",
    "ct",
    "mt",
    "user_login",
    "username",
    "login",
    "email",
    "user_email",
    "email_address",
    "customer_id",
    "member_id",
    "profile_id",
    "domain_userid",
    "network_userid",
    "user_ipaddress",
    "client_ip",
    "true_ip",
    "hardware_id",
    "installation_uuid",
    "instance_id",
    "instanceid",
    "instance_uuid",
    "client_id",
    "client_uuid",
    "idfv",
    "advertising_id",
    "aaid",
    "ifa",
    "ifad",
    "identifier_for_vendor",
    "browser_fingerprint",
    "device_fingerprint",
    "fingerprint_id",
    "_gid",
    "_fbp",
    "_fbc",
    "_ym_uid",
    "_ym_d",
    "_hjSession",
    "_hjSessionUser",
    "ajs_user_id",
    "ajs_anonymous_id",
    "amplitude_id",
    "mixpanel_distinct_id",
    "sharer_user_id",
    "sharer_uid",
    "sharer_id",
    "shared_by_id",
    "shared_by_uid",
    "share_from",
    "share_from_id",
    "referrer_user_id",
    "referrer_uid",
    "ref_user_id",
    "ref_uid",
    "inviter_id",
    "inviter_uid",
    "invited_by",
    "friend_id",
    "friend_uid",
    "follower_id",
    "follower_uid",
    "cross_device_id",
    "crossdevice_id",
    "device_graph_id",
    "identity_graph_id",
    "true_device_id",
    "unified_id",
    "unifiedid",
    "stitched_id",
    "stitched_user_id",
    "global_id",
    "globalid",
    "canvas_hash",
    "canvas_fingerprint",
    "webgl_hash",
    "webgl_fingerprint",
    "webrtc_ip",
    "webrtc_leak",
    "fonts_hash",
    "fonts_fingerprint",
    "plugins_hash",
    "plugins_fingerprint",
    "audio_hash",
    "audio_fingerprint",
    "gpu_hash",
    "gpu_fingerprint",
    "screen_hash",
    "screen_fingerprint",
    "timezone_offset",
    "language",
    "languages",
    "accept_language",
    "platform",
    "hardware_concurrency",
    "device_memory",
    "touch_support",
    "cookies_enabled",
    "do_not_track",
    "bot_score",
    "bot_detected",
    "automation_detected",
    "headless_detected",
    "proxy_detected",
    "vpn_detected",
    "tor_detected",
    "datacenter_ip",
    "proxy_ip",
    "vpn_ip",
    "is_proxy",
    "is_vpn",
    "is_tor",
    "is_datacenter",
    "connection_type",
    "proxy_level",
    "proxy_type",
    "identity_alignment_id",
    "alignment_id",
    "stitching_id",
    "matching_id",
    "resolved_user_id",
    "resolved_uid",
    "merged_user_id",
    "merged_uid",
    "canonical_user_id",
    "canonical_uid",
    "multi_account_token",
    "account_cluster_id",
    "user_cluster_id",
    "behavioral_hash",
    "behavioral_fingerprint",
    "pattern_id",
    "usage_pattern_id",
    "srsltid",
    "_bta_tid",
    "_bta_c",
    "trk_contact",
    "trk_msg",
    "trk_module",
    "trk_sid",
    "gdfms",
    "gdftrk",
    "gdffi",
    "redirect_log_mongo_id",
    "redirect_mongo_id",
    "sb_referer_host",
    "mkwid",
    "pcrid",
    "ef_id",
    "s_kwcid",
    "dm_i",
    "pk_campaign",
    "pk_kwd",
    "pk_keyword",
    "piwik_campaign",
    "piwik_kwd",
    "piwik_keyword",
    "mtm_campaign",
    "mtm_keyword",
    "mtm_source",
    "mtm_medium",
    "mtm_content",
    "mtm_cid",
    "mtm_group",
    "mtm_placement",
    "matomo_campaign",
    "matomo_keyword",
    "matomo_source",
    "matomo_medium",
    "matomo_content",
    "matomo_cid",
    "matomo_group",
    "matomo_placement",
    "mkevt",
    "mkcid",
    "mkrid",
    "campid",
    "toolid",
    "customid",
    "si",
    "sms_source",
    "sms_click",
    "sms_uph",
    "ndclid",
    "ScCid",
    "rtid",
    "irclickid",
    "vmcid",
    "tw_source",
    "tw_campaign",
    "tw_term",
    "tw_content",
    "tw_adid",
    "klar_source",
    "klar_cpid",
    "klar_adid",
    "trc_gcmp_id",
    "trc_gag_id",
    "trc_gad_id",
    "_r",
    "u_code",
    "preview_pb",
    "sharer_language",
    "_d",
    "share_item_id",
    "user_id",
    "sec_user_id",
    "item_author_type",
    "social_share_type",
    "share_iid",
    "share_link_id",
    "share_app_id",
    "ugbiz_name",
    "ug_btm",
    "link_reflow_popup_iteration_sharer",
    "enable_checksum"
]
