[bot]
token = "..."
src_url = "https://github.com/.../..."

[logging]
dirs = "info,hyper=warn,reqwest=warn,tokio_util::codec=warn"

[chat]
receiver_chat_id = 123

[timeouts]
video_download = 420
audio_download = 420
send_by_fs = 210
send_by_id = 360

[blacklisted]
domains = ["t.me", "2girls1cup.ca"]

[domains_with_reactions]
domains = [
    "vk.com", "vkvideo.ru", "ok.ru", "rutube.ru", "max.ru", "m.vkvideo.ru",
    "youtube.com", "youtu.be", "m.youtube.com", "music.youtube.com", "studio.youtube.com",
    "rt.pornhub.com", "rt.pornhub.org", "pornhub.com",
    "vm.tiktok.com", "vt.tiktok.com", "tiktok.com", 
    "x.com", "facebook.com",
    "share.google", "drive.google.com",
    "vxinstagram.com",  "fxtwitter.com", "fixupx.com", "fxbsky.app",
    "coub.com",
]

[random_cmd]
domains = [
    "vk.com", "vkvideo.ru", "ok.ru", "rutube.ru", "max.ru", "m.vkvideo.ru",
    "youtube.com", "youtu.be", "m.youtube.com", "music.youtube.com", "studio.youtube.com",
    "vm.tiktok.com", "vt.tiktok.com", "tiktok.com", 
    "vxinstagram.com", "fxtwitter.com", "fixupx.com", "fxbsky.app"
    "coub.com", 
]

[[replace_domains]]
from = '^(?:.*\.)?instagram\.(tv|net|com|org)$|^instagr\.am$'
to = "vxinstagram.com"

[[replace_domains]]
from = '^(?:.*\.)?twitter\.com$'
to = "fxtwitter.com"

[[replace_domains]]
from = '^(?:.*\.)?x\.com$'
to = "fixupx.com"

[[replace_domains]]
from = '^(?:.*\.)?bsky\.app$'
to = "fxbsky.app"

[yt_dlp]
max_file_size = 5000000
executable_path = "./yt-dlp/executable"
cookies_path = "./cookies"

[database]
user = "..."
password = "..."
# You can use "127.0.0.1" if the database is running on the same network.
# If the database is running in docker, you can use the database container name as the host.
host = "ytdl_tg_bot.postgres"
port = 5432
database = "api"

[yt_toolkit]
url = "http://ytdl_tg_bot.yt_toolkit_api:8080"
# url = "http://127.0.0.1:8080"

[yt_pot_provider]
url = "http://ytdl_tg_bot.yt_pot_provider_api:4416"
# url = "http://127.0.0.1:4416"

[telegram_bot_api]
url = "http://ytdl_tg_bot.telegram_bot_api:8081"
# url = "https://api.telegram.org"
api_id = "..."
api_hash = "..."

[tracking_params]
params = [
    # UTM
    "utm_source",
    "utm_medium",
    "utm_campaign",
    "utm_term",
    "utm_content",
    "utm_id",
    "utm_source_platform",
    "utm_creative_format",
    "utm_marketing_tactic",
    # Google
    "gclid",
    "gclsrc",
    "dclid",
    "gbraid",
    "wbraid",
    "_ga",
    "_gl",
    # Facebook/Meta
    "fbclid",
    "fb_action_ids",
    "fb_action_types",
    "fb_source",
    "fb_ref",
    "action_object_map",
    "action_type_map",
    "action_ref_map",
    # Instagram
    "igshid",
    "igsh",
    "ig_rid",
    # TikTok
    "ttclid",
    "tt_content",
    "tt_medium",
    # YouTube
    "si",
    "feature",
    "kw",
    # Twitter/X
    "twclid",
    "t",
    "s",
    # LinkedIn
    "li_fat_id",
    "lipi",
    "licu",
    "trk",
    # Microsoft/Bing
    "msclkid",
    # Amazon
    "tag",
    "creative",
    "creativeASIN",
    "linkCode",
    "ref",
    "ref_",
    # Email Marketing
    "_ke",
    "vero_id",
    "vero_conv",
    "mc_cid",
    "mc_eid",
    # HubSpot
    "_hsenc",
    "_hsmi",
    "hmb_campaign",
    "hmb_medium",
    "hmb_source",
    # Marketo
    "mkt_tok",
    # Reddit
    "rdt_cid",
    # Pinterest
    "epik",
    # Snapchat
    "ScCid",
    # Generic
    "source",
    "campaign",
    "medium",
    "content",
    "term",
]
